### ISSUE TITLE
[QUESTION] How can i see english.lua file?

### ISSUE THREAD

**Issue by Blueberryy** [Metastruct/translation#1]
I wanna see all current text that i can translate

**Comment by SpiralP** [comment]
There is none because we just do `L"pirate"` in code.  You can find the english in the other files though like this https://github.com/Metastruct/translation/blob/master/lua/translations/japanese.lua#L2

**Comment by Blueberryy** [comment]
Korean have more strings that i can translate, i'll copy and translate from korean file

**Comment by Blueberryy** [comment]
Also, i remember i've seen some kind of translate window on server. You can do that ingame? You know command how can i open that window?

**Comment by SpiralP** [comment]
It looks like to open it you have to run lua, in console you can run `l translation.ShowEditor()` on metastruct, the lowercase L runs lua
